### ISSUE TITLE
ERROR: Failed to transform file using transform JetifyTransform

### ISSUE THREAD

**Issue by bkhezry** [pwittchen/prefser#128]
Hi,
I add version of 2.2.1 to my build gradle that migrate to androidx. during project syncing return this errors:

```
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'prefser-rx2-2.2.1.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform file 'prefser-rx2-2.2.1.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform file 'prefser-rx2-2.2.1.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app
```

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I have no idea what JetifyTransform is. I'll check it tomorrow during the day.

Regards

**Comment by pwittchen** [comment]
I'm not really sure if this problem is library issue. I've found one answer on SO. Please, check it out and verify if it applies to your project. Link: https://stackoverflow.com/a/51827551/1150795.

**Comment by bkhezry** [comment]
@pwittchen thanks for your reply. I just use [jitpack](https://jitpack.io/) for your library and with repository of jitpack, it work fine.

**Comment by pwittchen** [comment]
Ok, great!
