### ISSUE TITLE
Not working with AndroidX.

### ISSUE THREAD

**Issue by romanbjit** [pwittchen/prefser#130]

**Comment by pwittchen** [comment]
Thanks for the report. I'll have a look on that.

czw., 24 sty 2019, 04:44: Hawladar Roman <notifications@github.com>
napisał(a):

**Comment by pwittchen** [comment]
It is fixed by 74de9db550ff941083448c28c48b6daffaed7b6c.
Next release for RxJava2.x will be compatible with androidx.
