### ISSUE TITLE
More than 2 preferences observables

### ISSUE THREAD

**Issue by tsuharesu** [pwittchen/prefser#45]
One of the problems I'm currently having it that Prefser stores only 1 onSharedPreferencesChangeListener. According to [registerOnSharedPreferenceChangeListener](http://developer.android.com/reference/android/content/SharedPreferences.html#registerOnSharedPreferenceChangeListener(android.content.SharedPreferences.OnSharedPreferenceChangeListener)) when the reference is not stored somewhere, it will be garbage collected.

I'm trying to setup some observables throughout my app (currently 5 or so) and it is not really working. Do you have any advice about this?

**Comment by pwittchen** [comment]
I'll check that issue. In the meantime, you can check [`observe(final SharedPreferences preferences)` method and `observeDefaultPreferences()` method](https://github.com/pwittchen/prefser#subscribing-for-data-updates). After subscribing one of these methods, you can observe any changes in any preference of SharedPreferences. These Observables will generate key of changed preference.

**Comment by tsuharesu** [comment]
They all call the same method in the end, `observe`, that is changing Prefser.onChangeListener variable every time someone subscribe to it. 

Some more background on the issue: I have different classes using the same Prefser instance (injecting a Singleton via Dagger 2). So, various classes sharing the same instance and subscribing on different times.

I am implementing OnSharedPreferenceChangeListener on my classes (Activity, Presenter...) and things are working. No need to rush.

**Comment by tsuharesu** [comment]
@pwittchen maybe this is not even a bug and more of a guideline "Don't share prefser instance and observe preferences in various places". It's your call, really

**Comment by pwittchen** [comment]
Yeah, it's kind of guideline, but library should work as developers expect. After reading documentation, it seems to be quite easy fix, but I'll need to test updated version before pushing a change.

**Comment by pwittchen** [comment]
I've changed scope of the listener from whole class to `observe(...)` method. Moreover, I've added an example with many observables. Now, it should be fine. Updated library will be available in the next release on Maven Central soon.
