### ISSUE TITLE
Possible missed update with getAndObserve()

### ISSUE THREAD

**Issue by ypresto** [pwittchen/prefser#47]
This library uses Rx startWith() for observing and getting current value of share preferences.

https://github.com/pwittchen/prefser/blob/67144d5a2fd71284a233828f3416e3421f4cadc1/library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java#L144

`startWith(observe(), get())` (which is implemented as `concat(get(), observe())`) can miss update from shared preference change listener, because it only start observing after `get()` is completed.

https://github.com/ReactiveX/RxJava/issues/3017#issuecomment-117624457

It misses update when:

1. Call getAndObserve()
2. Observable of get() fetches value from shared preferences and stores it to local variable.
3. Another thread updates preference value.
4. Another thread notifies preference change, but Observable of observe() not subscribed yet.
5. onNext() of get() is called with preference value fetched at 2.
6. When Observable of get() is completed, then Observable of observe() is subscribed.
7. Latest value of preference is set at 3, but this value will not be notified until next update!

**Comment by pwittchen** [comment]
Thank you for reporting this issue. It's quite specific case and I haven't verified that, but probably you are right. I see, you referenced this issue in one of the issues of RxJava project, so we can watch it as see if it will be updated. Moreover, any Pull Request improving existing solution are welcome.

**Comment by ypresto** [comment]
I see. Thank you for cool library!
