### ISSUE TITLE
Wrong return type when null is used for default value

### ISSUE THREAD

**Issue by ypresto** [pwittchen/prefser#48]
We have just encountered a bug around type generics.

```diff
     public Observable<Boolean> observePreference() {
-        return mPrefser.getAndObserve(KEY, String.class, null); // emits String, but inferred as Observable<Boolean> by return type
+        return mPrefser.<String>getAndObserve(KEY, String.class, null)
+                .map(this::mapToBoolean);
     }
 ```

Second parameter of getAndObserve is raw type without type parameter: `Class`.
`Class<T>` should be used instead to make type inference work well.

But this causes unchecked assignment warnings when used with List.class, as type of List content is not specified.
Maybe related to issue about List type: #44.

**Comment by pwittchen** [comment]
Thank you for reporting this issue. I'll take a look on that.
