### ISSUE TITLE
Consider use of android support anotations

### ISSUE THREAD

**Issue by semanticer** [pwittchen/prefser#76]
Maybe use of @Nullable and @NonNull can be useful?

**Comment by pwittchen** [comment]
Thank you for creating new issue. We can consider using such annotations. Where you think they could be useful and why?

**Comment by semanticer** [comment]
From what I can see in Prefser class.

**Comment by semanticer** [comment]
I'm sorry for my vague description. I've added pull request to show what I meant. If you already ensure NonNulls with checkNotNull method, you can also signal this intent to clients.

**Comment by pwittchen** [comment]
It's done, so I'm closing this issue.
